Development add tfgrid client
threefoldtech/web3_proxy pull request #19
Opened 2023-04-12 09:08 UTC by MarioBassem

2023-04-17 07:36 UTC, DylanVerstraete requested changes
Looks good, please fix the merge conflics.

I also prefer we move out the tfgrid client specific code as dicussed here: https://github.com/threefoldtech/tfgrid-sdk-go/issues/76 in the next iteration

2023-04-19 08:03 UTC, brandonpille reviewed
Great work. Some comments.

2023-04-19 11:17 UTC, Omarabdul3ziz commented on scripts/tfgrid/capacity_filter.v
> +pub struct FilterOptions {
since these filters are used by both farmerbot and gridproxy. we used only the common filters in both. `certified` is not in gridproxy filtering.
and for `cru`: the filter for the capacity works by subtract the used resources from the total one. and since cpu cores can be over provisioning it will not be accurate. for example 5 machines each with 8 cores can be on a node that has only 32 cores. is there any suggestion on how to do this filter?

2023-04-19 11:17 UTC, Omarabdul3ziz commented on scripts/tfgrid/capacity_filter.v
> +	filter_options  FilterOptions // the passed request filters.
it was just an extra info. if the user only selected one filter. the return result will have the filter options he provide + the zero values for other filters he did not provide. just to see what is being filtered.
no need really i can remove it.

2023-04-19 12:10 UTC, Omarabdul3ziz commented on scripts/tfgrid/login.v
> +pub fn (mut client Login) load(credentials Credentials) ! {
it fails 
![image](https://user-images.githubusercontent.com/32527347/233070691-90011831-0364-4120-966b-49ef0cc59598.png)

2023-04-19 14:18 UTC, brandonpille commented on scripts/tfgrid/login.v
> +pub fn (mut client Login) load(credentials Credentials) ! {
I must have had an old version. Thanks Omar!

2023-04-19 14:24 UTC, brandonpille commented on scripts/tfgrid/capacity_filter.v
> +	filter_options  FilterOptions // the passed request filters.
Yes remove it please. The user send the options so he knows what he send.

2023-04-19 14:26 UTC, brandonpille commented on scripts/tfgrid/capacity_filter.v
> +pub struct FilterOptions {
The farmerbot handles that actually. I guess gridproxy does not? How much cpus do you ask for then?

2023-04-20 10:29 UTC, MarioBassem commented on scripts/tfgrid/k8s.v
> +// NOTE: not implemented
they could be added, but i would highly recommend we wait until we move the implementation code to the grid-client, because it will involve a lot of implementation details that, imo, shouldn't be in the server.

2023-04-20 10:34 UTC, MarioBassem commented on scripts/main.v
> +	// deploy_deployment := tfgrid.Deployment{
for deploying and updating, you need to first create a contract on the chain with the deployment hash, then send the deployment to the node. this call only does the second part, so the call will always fail if not preceded with a chain call.

for deleting, it is prohibited from zos side, currently you can only delete a deployment by deleting its contract. so the call is still there, but doesn't do anything.

at last, i uncommented all calls :D

2023-04-20 12:04 UTC, brandonpille commented on scripts/tfgrid/k8s.v
> +// NOTE: not implemented
Yes. Let's do that another time. Can you create an issue in web3_proxy to add those calls later?

2023-04-20 12:10 UTC, MarioBassem commented on scripts/tfgrid/k8s.v
> +// NOTE: not implemented
sure.
created here (https://github.com/threefoldtech/web3_proxy/issues/27)

2023-04-20 16:40 UTC, merged