Adds sftpgo sal
threefoldtech/web3_proxy pull request #72
Opened 2023-05-17 14:01 UTC by ashraffouda

2023-05-23 11:37 UTC, brandonpille commented on lib/sftpgo/users.v
> +	req := http.Request{
This is not json rpc 2.0 but http requests. Can you look at the other examples and do the same as those?

2023-05-24 09:26 UTC, DylanVerstraete commented
@ashraffouda  please update the base branch and move docs to right folder.

2023-05-24 12:35 UTC, ashraffouda commented on lib/sftpgo/users.v
> +	req := http.Request{
sftp only supports http calls

2023-05-24 12:52 UTC, DylanVerstraete commented on lib/sftpgo/users.v
> +	req := http.Request{
@brandonpille the SFTP go is a server extension that runs it's own process server over http (has nothing to do with the traditional rpc endpoint)

2023-05-25 07:37 UTC, brandonpille commented on lib/sftpgo/users.v
> +	req := http.Request{
Indeed but it's a bit strange that you send json rpc for all other clients in the web3 proxy and that you then have to do a http request for sftp. Maybe it would be better to wrap it in the web3_proxy server. So we just add a new client in the go server which sends the http request for us and returns the result. Then people who are using the web3 proxy server can just send json rpc.

2023-05-26 07:52 UTC, DylanVerstraete approved these changes
Already approving, some comments though

2023-05-26 07:52 UTC, DylanVerstraete commented on manual/src/SUMMARY.md
> +  - [sftpgo-sal](examples/sftpgo/sal.md)
Please update here so the examples are in a list (so they show up in the side navigation)

2023-05-26 07:52 UTC, DylanVerstraete commented on manual/src/examples/sftpgo/examples.md
> +- [Users](./users.md)
Also list all examples here

2023-05-28 11:27 UTC, sameh-farouk requested changes
since the JWT token is short lived, I suggest **handling the token expiration** (you will get a 401 HTTP response code once it expired you can handle this and create new token) or **better you can use API keys** as it is more suited for machine-to-machine communications (after getting the JWT token you can use it to create API key. more info [here](https://sftpgo.stoplight.io/docs/sftpgo/10d357162eaeb-add-api-key) and [here](https://github.com/drakkan/sftpgo/blob/main/docs/rest-api.md))

2023-05-30 08:21 UTC, DylanVerstraete commented
It's great to use an API-key indeed but can you also add a function to generate such a key?

2023-05-31 07:40 UTC, DylanVerstraete requested changes

2023-05-31 07:40 UTC, DylanVerstraete commented on lib/sftpgo/sftpgo.v
> +	println(key_data)
remove this println please

2023-05-31 07:40 UTC, DylanVerstraete commented on examples/sftpgo/main_api_key.v
> +		jwt: jwt
how to get the jwt?

2023-05-31 08:06 UTC, ashraffouda commented on examples/sftpgo/main_api_key.v
> +		jwt: jwt
added a comment how to generate it, https://github.com/threefoldtech/web3_proxy/pull/72/files#diff-6534a2f0fce21d741a860422eba51bb845db7c9af5c9ab3f192cc21b2cfac877R19

2023-05-31 08:09 UTC, DylanVerstraete commented on examples/sftpgo/main_api_key.v
> +		jwt: jwt
Can you add a helper method for it on the lib please? :-)

2023-05-31 14:39 UTC, DylanVerstraete approved these changes
Awesome! :ship: it

2023-05-31 14:55 UTC, merged